"use client";

import { useState } from "react";
import { Braces, Copy } from "lucide-react";
import { Button, Panel } from "@/components/ui";
import { useMesh } from "@/components/MeshProvider";

export function CodeCreator() {
  const { submitJob } = useMesh();
  const [prompt, setPrompt] = useState(""); const [result, setResult] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async () => { if (!prompt.trim()) return; setBusy(true); setMessage("Fund 0.01 SOL in escrow to begin…"); setResult(""); try { const job = await submitJob({ prompt, modelSource: "managed:code", budget: "0.01" }); if (job.error || !job.job) throw new Error(job.error || "Escrow funding failed."); setMessage("Escrow funded. Processing…"); const response = await fetch("/api/ai", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "code", prompt, jobId: job.job.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Code generation failed."); setResult(data.result); setMessage("Code generated."); } catch (error) { setMessage(error instanceof Error ? error.message : "Code generation failed."); } finally { setBusy(false); } };
  return <Panel className="mt-4"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">ComputeFi AI</p><h2 className="mt-2 font-display text-2xl italic text-ivory">Code creator</h2></div><Braces className="text-gold" size={24}/></div><p className="mt-3 max-w-2xl text-sm leading-relaxed text-stone">Generate code through ComputeFi&apos;s hosted AI. Your prompt and result stay in this session.</p><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} rows={4} placeholder="Example: Create a TypeScript utility that validates a Solana address, with tests." className="mt-6 w-full resize-none border border-ivory/10 bg-transparent px-4 py-3 text-sm text-ivory outline-none placeholder:text-stone/50 focus:border-gold/50"/><div className="mt-3 flex items-center gap-3"><Button onClick={submit} disabled={busy || !prompt.trim()}>{busy ? "Generating" : "Generate code"}</Button>{message ? <p className="text-sm text-stone">{message}</p> : null}</div>{result ? <div className="relative mt-6 border border-ivory/10 bg-black/20"><button onClick={() => navigator.clipboard.writeText(result)} className="absolute right-3 top-3 inline-flex items-center gap-2 text-[10px] uppercase tracking-[.12em] text-stone hover:text-ivory"><Copy size={12}/>Copy</button><pre className="max-h-[420px] overflow-auto p-4 pr-16 text-xs leading-relaxed text-ivory/85">{result}</pre></div> : null}</Panel>;
}
