"use client";

import { useState } from "react";
import { useWallet } from "@solana/wallet-adapter-react";
import { useWalletModal } from "@solana/wallet-adapter-react-ui";
import { Upload } from "lucide-react";
import { Button, Panel, Section, StatusPill } from "@/components/ui";
import { useMesh } from "@/components/MeshProvider";

export function RentView() {
  const { connected } = useWallet(); const { setVisible } = useWalletModal(); const { workers, jobs, tabId, submitJob } = useMesh();
  const [prompt, setPrompt] = useState(""); const [modelSource, setModelSource] = useState(""); const [budget, setBudget] = useState(""); const [fileName, setFileName] = useState(""); const [fileData, setFileData] = useState<string | null>(null); const [message, setMessage] = useState(""); const [posting, setPosting] = useState(false);
  const chooseFile = async (file: File | undefined) => { if (!file) return; if (file.size > 1024 * 1024) { setMessage("Keep uploads at 1 MB or less."); return; } setFileName(file.name); setFileData(await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); })); };
  const submit = async () => { if (!connected) { setVisible(true); return; } if (!prompt.trim()) return; setPosting(true); setMessage("Confirm the SOL payment in your wallet. The job posts after it is verified."); const result = await submitJob({ prompt, modelSource, fileName, fileData, budget }); setPosting(false); if (result.error) { setMessage(result.error); return; } setPrompt(""); setModelSource(""); setBudget(""); setFileData(null); setFileName(""); setMessage("Payment verified. Your job is on the board."); };
  return <div>
    <section className="mx-auto max-w-page px-6 pb-10 pt-24 md:pt-32"><p className="eyebrow">Rent compute</p><h1 className="mt-5 max-w-3xl font-display text-4xl font-light italic leading-[1.1] text-ivory md:text-6xl">Send a job. Pay in SOL. Track the result.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-stone">Choose a model, describe the work, and set a SOL budget. Your wallet sends the budget to escrow first. An available worker takes the job.</p></section>
    <Section className="pt-4"><Panel className="mb-4"><p className="eyebrow">How it works</p><div className="mt-4 grid gap-4 md:grid-cols-3 text-sm text-stone"><p><span className="text-gold">1.</span> Say what you need and choose the model.</p><p><span className="text-gold">2.</span> Approve the SOL payment to escrow.</p><p><span className="text-gold">3.</span> An available worker takes the job.</p></div></Panel><div className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]"><Panel><h2 className="font-display text-2xl italic text-ivory">New job</h2><form className="mt-8 space-y-6" onSubmit={(e) => { e.preventDefault(); submit(); }}>
      <label className="block"><span className="text-[10px] uppercase tracking-[0.2em] text-stone">What should run?</span><textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} rows={5} placeholder="Example: Summarize these support tickets and return JSON with priority and theme." className="mt-2 w-full resize-none border border-ivory/10 bg-transparent px-4 py-3 text-sm text-ivory outline-none placeholder:text-stone/50 focus:border-gold/50" /></label>
      <label className="block"><span className="text-[10px] uppercase tracking-[0.2em] text-stone">Hugging Face model ID or link</span><input value={modelSource} onChange={(e) => setModelSource(e.target.value)} placeholder="meta-llama/Llama-3.1-8B-Instruct" className="mt-2 w-full border border-ivory/10 bg-transparent px-4 py-2.5 text-sm text-ivory outline-none placeholder:text-stone/50 focus:border-gold/50" /><p className="mt-2 text-xs text-stone">Recommended: paste a Hugging Face model ID. A direct model URL also works.</p></label>
      <label className="block"><span className="text-[10px] uppercase tracking-[0.2em] text-stone">Optional input file</span><span className="mt-2 flex cursor-pointer items-center gap-2 border border-dashed border-ivory/20 px-4 py-3 text-sm text-stone hover:border-gold/60 hover:text-ivory"><Upload size={15}/>{fileName || "Upload a small prompt list or input file (up to 1 MB)"}<input type="file" className="sr-only" onChange={(e) => chooseFile(e.target.files?.[0])}/></span></label>
      <label className="block"><span className="text-[10px] uppercase tracking-[0.2em] text-stone">Budget in SOL</span><input value={budget} onChange={(e) => setBudget(e.target.value)} placeholder="0.01" inputMode="decimal" className="mt-2 w-full border border-ivory/10 bg-transparent px-4 py-2.5 text-sm text-ivory outline-none" /><p className="mt-2 text-xs text-stone">SOL is held in escrow and released to the worker after verified completion.</p></label>
      <Button type="submit" className="w-full py-3" disabled={!prompt.trim() || posting}>{posting ? "Waiting for wallet" : connected ? "Pay SOL & post job" : "Connect wallet to pay"}</Button>{message ? <p className="text-sm text-stone">{message}</p> : null}
    </form></Panel>
    <Panel><div className="flex items-center justify-between"><h2 className="font-display text-2xl italic text-ivory">Available workers</h2><StatusPill live={workers.length > 0}>{workers.length ? `${workers.length} online` : "None online"}</StatusPill></div><p className="mt-4 text-sm text-stone">Only workers with a fresh heartbeat are listed here.</p>{workers.length === 0 ? <p className="mt-6 text-sm text-stone">No machine is available yet. On Earn, someone can share a tab or run the PC worker.</p> : <ul className="mt-6 divide-y divide-ivory/10 border-y border-ivory/10">{workers.map((w) => <li key={w.id} className="py-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-ivory">{w.adapter}{w.id === tabId ? " (this tab)" : ""}</p><p className="mt-1 text-xs text-stone">{w.kind === "native" ? "PC worker" : "Browser worker"}{w.cores != null ? ` · ${w.cores} cores` : ""}</p></div><StatusPill live={w.status === "idle"}>{w.status === "busy" ? "Working" : "Available"}</StatusPill></div></li>)}</ul>}</Panel></div>
    <Panel className="mt-4"><div className="flex items-center justify-between"><h2 className="font-display text-2xl italic text-ivory">Job board</h2><StatusPill live={jobs.some((j) => j.status !== "done")}>{jobs.length} total</StatusPill></div>{jobs.length === 0 ? <p className="mt-6 text-sm text-stone">Your paid jobs will appear here. The oldest open job goes to the next available worker.</p> : <ul className="mt-6 divide-y divide-ivory/10 border-y border-ivory/10">{jobs.map((job) => <li key={job.id} className="py-5"><div className="flex flex-wrap items-start justify-between gap-3"><p className="max-w-2xl text-sm text-ivory">{job.prompt}</p><StatusPill live={job.status === "running"}>{job.status === "open" ? "Waiting" : job.status === "running" ? "Working" : "Complete"}</StatusPill></div><p className="mt-2 text-xs text-stone">{job.modelSource ? `${job.modelSource} · ` : ""}{job.fileName ? `${job.fileName} · ` : ""}{job.budget} SOL · {job.workerId ? "worker assigned" : "waiting for an available worker"}</p></li>)}</ul>}</Panel></Section></div>;
}
